# fly.toml app configuration file generated for strong40-2 on 2025-08-16T21:57:31Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'strong40-2'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1